version: 2

project_name: pprof-analyzer

before:
  hooks:
    - go mod tidy

builds:
  - id: pprof-analyzer
    main: ./cmd/pprof-analyzer
    binary: pprof-analyzer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: pprof-analyzer
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: Gabriel-Schiestl
    name: pprof-analyzer
  draft: false
  prerelease: auto
